# Generated by Django 4.1.7 on 2023-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default_dish_image/default.png', null=True, upload_to='uploads/'),
        ),
    ]
