# Generated by Django 4.1.7 on 2023-05-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_busy_table_reserved_alter_table_table_qr_code_and_more'),
        ('order', '0004_alter_order_paid_amount_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='table.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'En attente'), (1, 'En cours'), (2, 'Envoyé en attente du paiement'), (3, 'Payé')], default=0),
        ),
    ]
