# Generated by Django 4.1.7 on 2023-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_table_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, "En attente d'acceptation"), (1, 'En cours de préparation'), (2, 'Envoyé et en attente de paiement'), (3, 'Paiement effectué')], default=0),
        ),
    ]
