# Generated by Django 4.1.7 on 2023-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
