# Generated by Django 4.1.7 on 2023-05-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_QR_Code',
            field=models.ImageField(blank=True, null=True, upload_to='media/table/qrCodes/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
